title: Amruth Acharya
description: Functional consultant experience across P2P, SLP, CLM, and CIG.
theme: jekyll-theme-cayman   # Try also:
# theme: jekyll-theme-minimal
# theme: jekyll-theme-slate
# theme: jekyll-theme-modernist
