title: "Amruth Acharya"
description: |
  <span style='font-size:16px; color:#111111;'>SAP Ariba Consultant | P2P | SLP | CLM | CIG</span>

theme: minimal-mistakes-jekyll
#theme: jekyll-theme-primer
#jekyll-theme-cayman   # Try also:
# theme: jekyll-theme-minimal
# theme: jekyll-theme-slate
# theme: jekyll-theme-modernist
